package load

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/Abuaslamtech/capacitylab/internal/config"
)

// K6Adapter generates and executes k6 test scripts for advanced traffic simulation.
type K6Adapter struct {
	cfg *config.Config
}

var _ StageRunner = (*K6Adapter)(nil)

// NewK6Adapter creates an adapter for running load using k6 CLI
func NewK6Adapter(cfg *config.Config) *K6Adapter {
	return &K6Adapter{cfg: cfg}
}

// IsAvailable checks if the k6 binary is present in PATH
func (k *K6Adapter) IsAvailable() bool {
	_, err := exec.LookPath("k6")
	return err == nil
}

// GenerateScript transpiles capacitylab.yaml scenarios into a standard k6 JavaScript execution script
func (k *K6Adapter) GenerateScript(vus int, duration time.Duration) string {
	baseURL := strings.TrimRight(k.cfg.Application.URL, "/")

	var script strings.Builder
	script.WriteString("// Auto-generated by CapacityLab k6 Adapter\n")
	script.WriteString("import http from 'k6/http';\n")
	script.WriteString("import { sleep, check } from 'k6';\n\n")

	// Export test options
	script.WriteString(fmt.Sprintf(`export const options = {
  vus: %d,
  duration: '%s',
  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'p(99)'],
};

`, vus, duration.String()))

	// Export default scenario function
	script.WriteString("export default function () {\n")
	script.WriteString("  const session = {};\n")

	for i, sc := range k.cfg.Scenarios {
		script.WriteString(fmt.Sprintf("  // Scenario %d: %s (weight: %d%%)\n", i+1, sc.Name, sc.Weight))
		for _, rawStep := range sc.Flow {
			parsed, err := parseStep(rawStep)
			if err != nil {
				continue
			}

			fullURL := baseURL + parsed.Path
			switch parsed.Method {
			case "POST":
				bodyStr := "{}"
				if len(parsed.Body) > 0 {
					bodyStr = string(parsed.Body)
				}
				script.WriteString(fmt.Sprintf("  {\n    const res = http.post('%s', %s, { headers: { 'Content-Type': 'application/json' } });\n", fullURL, string(bodyStr)))
				script.WriteString("    check(res, { 'status is 2xx/3xx': (r) => r.status < 400 });\n  }\n")
			default:
				script.WriteString(fmt.Sprintf("  {\n    const res = http.get('%s');\n", fullURL))
				script.WriteString("    check(res, { 'status is 2xx/3xx': (r) => r.status < 400 });\n  }\n")
			}
		}
	}

	thinkSec := k.cfg.Workload.Pacing.ThinkTimeMin.Seconds()
	if thinkSec <= 0 {
		thinkSec = 0.2
	}
	script.WriteString(fmt.Sprintf("  sleep(%.2f);\n", thinkSec))
	script.WriteString("}\n")

	return script.String()
}

// RunStage executes a k6 subprocess with JSON summary output
func (k *K6Adapter) RunStage(ctx context.Context, vus int, duration time.Duration) (*StageMetrics, error) {
	if !k.IsAvailable() {
		return nil, fmt.Errorf("k6 binary not found in PATH")
	}

	tempDir := os.TempDir()
	scriptFile := filepath.Join(tempDir, fmt.Sprintf("capacitylab_k6_%d.js", time.Now().UnixNano()))
	summaryFile := filepath.Join(tempDir, fmt.Sprintf("capacitylab_k6_summary_%d.json", time.Now().UnixNano()))

	scriptContent := k.GenerateScript(vus, duration)
	if err := os.WriteFile(scriptFile, []byte(scriptContent), 0644); err != nil {
		return nil, fmt.Errorf("failed to write k6 script: %w", err)
	}
	defer os.Remove(scriptFile)
	defer os.Remove(summaryFile)

	cmd := exec.CommandContext(ctx, "k6", "run", "--summary-export", summaryFile, scriptFile)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("k6 run failed: %w (output: %s)", err, string(out))
	}

	data, err := os.ReadFile(summaryFile)
	if err != nil {
		return nil, fmt.Errorf("failed to read k6 summary: %w", err)
	}

	var summary struct {
		Metrics struct {
			HTTPReqs struct {
				Values struct {
					Count float64 `json:"count"`
					Rate  float64 `json:"rate"`
				} `json:"values"`
			} `json:"http_reqs"`
			HTTPReqDuration struct {
				Values struct {
					Med float64 `json:"med"`
					P90 float64 `json:"p(90)"`
					P95 float64 `json:"p(95)"`
					P99 float64 `json:"p(99)"`
				} `json:"values"`
			} `json:"http_req_duration"`
			HTTPReqFailed struct {
				Values struct {
					Rate float64 `json:"rate"`
				} `json:"values"`
			} `json:"http_req_failed"`
		} `json:"metrics"`
	}

	if err := json.Unmarshal(data, &summary); err != nil {
		return nil, fmt.Errorf("failed to decode k6 summary JSON: %w", err)
	}

	return &StageMetrics{
		VUs:           vus,
		Duration:      duration,
		TotalRequests: int64(summary.Metrics.HTTPReqs.Values.Count),
		RPS:           summary.Metrics.HTTPReqs.Values.Rate,
		P50Ms:         summary.Metrics.HTTPReqDuration.Values.Med,
		P90Ms:         summary.Metrics.HTTPReqDuration.Values.P90,
		P95Ms:         summary.Metrics.HTTPReqDuration.Values.P95,
		P99Ms:         summary.Metrics.HTTPReqDuration.Values.P99,
		ErrorPercent:  summary.Metrics.HTTPReqFailed.Values.Rate * 100.0,
	}, nil
}
